# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestDiariodeenxaquecaCRUDmedicacao():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}
    
    def teardown_method(self, method):
        self.driver.quit()
    
    def test_diariodeenxaquecaCRUDmedicacao(self):
        print("=" * 60)
        print("INICIANDO TESTE CRUD COMPLETO DE MEDICAÇÃO")
        print("=" * 60)

        print("\n1. Abrindo página inicial...")
        self.driver.get("http://localhost:3000/")
        self.driver.set_window_size(1184, 1040)
        print("Página inicial carregada")
        time.sleep(3)

        print("\n2. Interagindo com campo de email...")
        self.driver.find_element(By.ID, "email").click()
        element = self.driver.find_element(By.ID, "email")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).click_and_hold().perform()
        element = self.driver.find_element(By.ID, "email")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.ID, "email")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).release().perform()
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys(
            "usuario_testeCRUD@email.com")
        print("Email preenchido")
        time.sleep(1)

        print("\n3. Preenchendo campo de senha...")
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("12345678")
        print("Senha preenchida")
        time.sleep(1)

        print("\n4. Clicando em login...")
        self.driver.find_element(By.CSS_SELECTOR, ".inline-flex").click()
        print("Tentativa de login realizada")
        time.sleep(5)  # Aumentado para esperar resposta do login

        print("\n5. Clicando em 'Cadastre-se'...")
        # Tentar diferentes seletores para o link de cadastro
        try:
            self.driver.find_element(By.LINK_TEXT, "Cadastre-se").click()
        except:  # pylint: disable=bare-except
            try:
                self.driver.find_element(By.PARTIAL_LINK_TEXT,
                                         "Cadastre").click()
            except:  # pylint: disable=bare-except
                # Procurar por qualquer link que contenha "cadastro" ou similar
                links = self.driver.find_elements(By.TAG_NAME, "a")
                for link in links:
                    if "cadastre" in link.text.lower() or \
                        "registro" in link.text.lower() or "signup" in \
                        link.text.lower():
                        link.click()
                        break
                else:
                    raise Exception("Link de cadastro não encontrado")
        print("Página de cadastro acessada")
        time.sleep(2)

        print("\n6. Preenchendo formulário de cadastro...")
        self.driver.find_element(By.ID, "name").click()
        self.driver.find_element(By.ID, "name").send_keys("Usuario")
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys(
            "usuario_testeCRUD@email.com")
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("12345678")
        self.driver.find_element(By.ID, "confirmPassword").click()
        self.driver.find_element(By.ID, "confirmPassword").send_keys(
            "12345678")
        print("Formulário de cadastro preenchido")
        time.sleep(1)

        print("\n7. Clicando em cadastrar...")
        self.driver.find_element(By.CSS_SELECTOR, ".inline-flex").click()
        print("Usuário cadastrado")
        time.sleep(3)

        print("\n8. Interagindo com elementos da página...")
        self.driver.find_element(By.CSS_SELECTOR, ".bg-primary").click()
        print("Botão primário clicado")
        time.sleep(2)

        print("\n9. Fazendo login após cadastro...")
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys(
            "usuario_testeCRUD@email.com")
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("12345678")
        self.driver.find_element(By.CSS_SELECTOR, ".inline-flex").click()
        print("Login realizado com sucesso")
        time.sleep(3)

        print("\n10. Acessando página de medicações...")
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".inline-flex:nth-child(6)").click()
        print("Página de medicações acessada")
        time.sleep(2)

        print("\n11. Criando nova medicação...")
        self.driver.find_element(By.CSS_SELECTOR, ".shadow-md").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".shadow-md")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element_with_offset(element, 0, 0).perform()
        self.driver.find_element(By.ID,
                                 "medication-name").send_keys("paracetamol")
        self.driver.find_element(By.ID, "medication-dosage").click()
        self.driver.find_element(By.ID, "medication-dosage").send_keys("400mg")
        print("Formulário de medicação preenchido")
        time.sleep(1)

        print("\n12. Salvando medicação...")
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".flex-col-reverse > .bg-\\[\\#6C63FF\\]"
                                 ).click()
        print("Medicação criada")
        time.sleep(2)

        print("\n13. Editando medicação...")
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".hover\\3Atext-\\[\\#6C63FF\\]").click()
        self.driver.find_element(By.ID,
                                 "medication-name").send_keys(
                                    "paracetamol para teste")
        print("Nome da medicação editado")
        time.sleep(1)

        print("\n14. Salvando edição...")
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".bg-\\[\\#6C63FF\\]:nth-child(2)").click()
        element = self.driver.find_element(By.CSS_SELECTOR,
                                           ".bg-\\[\\#6C63FF\\]:nth-child(2)")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element_with_offset(element, 0, 0).perform()
        print("Edição salva")
        time.sleep(2)

        print("\n15. Excluindo medicação...")
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".hover\\3Atext-\\[\\#E74C3C\\]").click()
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".bg-\\[\\#E74C3C\\]").click()
        print("Medicação excluída")
        time.sleep(2)

        print("\n16. Excluindo usuário...")
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".inline-flex:nth-child(8)").click()
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".focus-visible\\3Aring-destructive\\/20"
                                 ).click()
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".flex > .text-primary-foreground").click()
        print("Usuário excluído")
        time.sleep(3)

        print("\n" + "=" * 60)
        print("TESTE CRUD COMPLETO DE MEDICAÇÃO CONCLUÍDO!")
        print("=" * 60)
