# Generated by Selenium IDE
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC


class TestDiariodeenxaquecaCRUDgatilho():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}
    
    def teardown_method(self, method):
        self.driver.quit()
    
    def test_diariodeenxaquecaCRUDgatilho(self):
        print("=" * 60)
        print("INICIANDO TESTE CRUD DE GATILHOS DE ENXAQUECA")
        print("=" * 60)

        print("\n1. Abrindo página inicial...")
        self.driver.get("http://localhost:3000/")
        self.driver.set_window_size(1617, 1040)
        print("Página inicial carregada")
        time.sleep(3)

        print("\n2. Fazendo login...")
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys(
            "usuario_testeCRUD@email.com")
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("123456789")
        self.driver.find_element(By.CSS_SELECTOR, ".inline-flex").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".inline-flex")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element_with_offset(element, 0, 0).perform()
        print("Tentativa de login realizada")
        time.sleep(5)

        print("\n3. Acessando página de cadastro...")
        self.driver.find_element(By.LINK_TEXT, "Cadastre-se").click()
        print("Página de cadastro acessada")
        time.sleep(2)

        print("\n4. Preenchendo formulário de cadastro...")
        self.driver.find_element(By.ID, "name").click()
        self.driver.find_element(By.ID, "name").send_keys(
            "usuario_testeCRUD@email.com")
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys(
            "usuario_testeCRUD@email.com")
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("12345678")
        self.driver.find_element(By.ID, "confirmPassword").click()
        self.driver.find_element(By.ID, "confirmPassword"
                                 ).send_keys("12345678")
        print("Formulário preenchido")
        time.sleep(1)

        print("\n5. Clicando em cadastrar...")
        self.driver.find_element(By.CSS_SELECTOR, ".inline-flex").click()
        print("Usuário cadastrado")
        time.sleep(3)

        print("\n6. Fazendo login após cadastro...")
        self.driver.find_element(By.CSS_SELECTOR, ".bg-primary").click()
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys(
            "usuario_testeCRUD@email.com")
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("12345678")
        self.driver.find_element(By.CSS_SELECTOR, ".inline-flex").click()
        print("Login realizado")
        time.sleep(3)

        print("\n7. Acessando seção de gatilhos...")
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".rounded-md:nth-child(5)").click()
        print("Página de gatilhos acessada")
        time.sleep(2)

        print("\n8. Iniciando criação de novo gatilho...")
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".hover\\3A bg-\\[\\#5850E6\\]").click()
        print("Formulário de criação de gatilho aberto")
        time.sleep(2)

        print("\n9. Preenchendo nome do gatilho...")
        self.driver.find_element(By.ID, "trigger-name"
                                 ).send_keys("Gatilho Teste")
        print("Nome preenchido: Gatilho Teste")
        time.sleep(1)

        print("\n10. Salvando gatilho...")
        WebDriverWait(self.driver, 10).until(
            EC.element_to_be_clickable((By.CSS_SELECTOR,
                                        ".bg-\\[\\#6C63FF\\]:nth-child(2)"))
        )
        button = self.driver.find_element(By.CSS_SELECTOR,
                                          ".bg-\\[\\#6C63FF\\]:nth-child(2)")
        self.driver.execute_script("arguments[0].click();", button)
        print("Gatilho salvo")
        time.sleep(5)

        print("\n11. Editando gatilho...")
        WebDriverWait(self.driver, 10).until(
            EC.element_to_be_clickable((By.CSS_SELECTOR,
                                        ".bg-\\[\\#6C63FF\\]:nth-child(2)"))
        )
        button = self.driver.find_element(By.CSS_SELECTOR,
                                          ".bg-\\[\\#6C63FF\\]:nth-child(2)")
        self.driver.execute_script("arguments[0].click();", button)
        self.driver.find_element(By.ID, "trigger-name"
                                 ).send_keys("Gatilho Teste para excluir")
        self.driver.find_element(By.ID, "trigger-name").send_keys(Keys.ENTER)
        print("Nome alterado para: Gatilho Teste para excluir")
        time.sleep(1)

        print("\n12. Excluindo gatilho...")
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".hover\\3Atext-\\[\\#E74C3C\\]").click()
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".bg-\\[\\#E74C3C\\]").click()
        print("Gatilho excluído")
        time.sleep(2)

        print("\n13. Excluindo usuário...")
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".inline-flex:nth-child(8)").click()
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".focus-visible\\3Aring-destructive\\/20"
                                 ).click()
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".flex > .text-primary-foreground").click()
        print("Usuário excluído")
        time.sleep(3)

        print("\n" + "=" * 60)
        print("TESTE CRUD DE GATILHOS CONCLUÍDO!")
        print("=" * 60)
